name: Frontend Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.0.0'
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
        working-directory: ./frontend
      # - name: Run tests
      #   run: pnpm test
      #   working-directory: ./frontend
      - name: build
        run: pnpm build
        working-directory: ./frontend
